//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_LAB_WEEK_4 {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label label;
		
		protected System.Web.UI.WebControls.TextBox inputCurrency;
		
		protected System.Web.UI.WebControls.Label fromLabel;
		
		protected System.Web.UI.WebControls.DropDownList fromCurrencyDropDown;
		
		protected System.Web.UI.WebControls.Label labelAns;
	}
}
